name: imblinlin
version: 1.1.0+2
publish_to: 'none'
description: Blinlin WuKongIM realtime chat Flutter application.

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.3
  intl: ^0.20.1
  cached_network_image: ^3.4.1
  crypto: ^3.0.6
  encrypt: ^5.0.3
  wukongimfluttersdk: ^1.7.9
  video_player: ^2.9.2
  image_picker: ^1.1.2
  flutter_webrtc: any
  file_picker: ^8.1.7
  cross_file: ^0.3.5+2
  path_provider: ^2.1.5
  record: ^7.1.0
  audioplayers: ^6.1.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0
  webview_flutter: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tsdd/common/
    - assets/tsdd/chat/
    - assets/gif_stickers/
